version: '3.8'

services:
  gestao-rodagem:
    container_name: api-catalogo
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: catalogo
      POSTGRES_USER: catalogo
      POSTGRES_DB: catalogo-db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
